### ISSUE TITLE
"Not enough quota is available to process this command" when launching for the first time

### ISSUE THREAD

**Issue by Jofluff** [Lewinator56/StormLoader#11]
It's a fresh install and as the title says, I get the error when I try to launch it. Log is attached.
[log.txt](https://github.com/Lewinator56/StormLoader/files/9823821/log.txt)

**Comment by Lewinator56** [comment]
Ensure you have enough space on the drive. Also make sure you extracted the zip before running stormloader. If that fails, reboot, windows might just be being funny.

**Comment by Jofluff** [comment]
Tried all that before I posted here. I have plenty of space and I did reboot windows after it failed to launch. I'm not sure what to do now

**Comment by Lewinator56** [comment]
Potentially check your page file size, if you have none set this might cause this error. It's not a bug in my code, the stack trace in the log is all related to win32 methods called at application startup.

You can check the page file size under the performance settings for Windows.

**Comment by Jofluff** [comment]
Seems to be working now. It was initially set to none, then I set it to 'System managed' and it worked enough to set the game directory. The issue popped up again and I set a higher limit. Thanks for the help.
