### ISSUE TITLE
Access to itesm is restricted

### ISSUE THREAD

**Issue by Auta5tic** [Lewinator56/StormLoader#14]
![2023-02-21](https://user-images.githubusercontent.com/109634808/220514057-6969268d-ddd0-4881-ab56-0db2b5c4449e.png)

**Comment by Lewinator56** [comment]
This is a permissions error, it's not expected under normal usage conditions. Where have you got stormloader installed? Make sure it's not in a directory that requires admin rights to access. If that fails, run it as administrator.

**Comment by Auta5tic** [comment]
I have it installed in my downloads, where do i move it? and how do i run it as an administrator?

**Comment by Auta5tic** [comment]
never mind it works now
