### ISSUE TITLE
Stormloader crashes when loading worlds

### ISSUE THREAD

**Issue by KingTasaz** [Lewinator56/StormLoader#17]
Whenever I try and load into a world (whether that be singleplayer, multiplayer, joining a friend, or creating a world), it always crashes around 63% or once it says "spawning". I managed to get into my friends world once, but then it crashed after a bit and I couldnt get in again. Even with all mods disabled I cant get into a world.

I've tried redownloading Stormloader and the mods and it still doesnt work. Even launching normally from steam (not using stormloader) it doesnt work.

**Comment by Lewinator56** [comment]
Stormloader does not modify core game files and thus could not cause a crash. The only potential cause could be missing tiles from uninstalling a mod that modifies tiles. I suggest you verify the game files through steam.
