### ISSUE TITLE
How to make meshes

### ISSUE THREAD

**Issue by hzlayer** [Lewinator56/StormLoader#2]
THIS is not a issue I do not know how you get the meshes in the .mesh format Blender cannot open that format and I've tried online converters and they don't work.

**Comment by Lewinator56** [comment]
Hi! sorry for this late reply, have you joined the discord? https://discord.gg/9HS7cb6 

I have released a tool that converts .obj files to .mesh files, if yo uwant to go the other way, there is no released tool yet, but you can simply export the mesh you wish to edit from stormworks anyway.

Hope this helps!
