### ISSUE TITLE
fixed

### ISSUE THREAD

**Issue by githubguy3** [Lewinator56/StormLoader#20]
ive activated the mods, there's a green checkmark to the left but they aren't working

**Comment by Lewinator56** [comment]
Make sure the path to stormworks is set correctly in stormloader's settings

**Comment by githubguy3** [comment]
how do i know if its correct? what should it look like?

**Comment by githubguy3** [comment]
also thanks for the quick response

**Comment by githubguy3** [comment]
nevermind, i think i got it

**Comment by githubguy3** [comment]
its not working,

**Comment by Lewinator56** [comment]
Can you attach your log file from stormloader

**Comment by githubguy3** [comment]
what do you mean by that?

**Comment by githubguy3** [comment]
how do i access the log file

**Comment by githubguy3** [comment]
i'm not very familiar with this stuff

**Comment by githubguy3** [comment]
what do you want me to do?

**Comment by githubguy3** [comment]
[log.txt](https://github.com/Lewinator56/StormLoader/files/13275258/log.txt)
