### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by githubguy3** [Lewinator56/StormLoader#21]
so i got this error when i tried to install original engine sounds mod "Could not find a part of the path './Extracted/Original Engine Sounds Mod  - Prodigy Industries /metadata.xml'."

**Comment by Lewinator56** [comment]
Ok that implies that the mod is missing it's metadata file, this is unlikely an issue with stormloader but one with the mod itself

**Comment by githubguy3** [comment]
ok thanks
