### ISSUE TITLE
Game crash when teleporting to FJ Warner Docks

### ISSUE THREAD

**Issue by darek2981** [Lewinator56/StormLoader#22]
My game crashes completely when teleporting to FJ Warner Docks
not only when teleporting but if i walk on foot too close it crashes (sorry for bad english)

**Comment by Lewinator56** [comment]
Do you have any mods loaded that replace tiles? 

If not I suggest validating the game files.

I only ever had crashes when tiles were corrupted in my testing.

**Comment by darek2981** [comment]
Validating the game files didn't help but completely reinstalling stormworks did the job.
Thank's for help.

**Comment by darek2981** [comment]
Validating the game files didn't help but completely reinstalling stormworks did the job.
Thank's for help.
