### ISSUE TITLE
mod loader crashes whenever i click "get" on a mod from the repo

### ISSUE THREAD

**Issue by Spykiller45** [Lewinator56/StormLoader#3]
my system uses an AMD ryzen 3800XT cpu and i have all my drivers up to date..so i think your loader is just broken on amd systems

**Comment by Lewinator56** [comment]
ill check this, but that shouldn't be the case, ive developed it on a ryzen system, can you put the log here, or if you are on discord, DM me it

**Comment by Spykiller45** [comment]
Reinstalled storloader so it shares the same drive on win as stormworks and now it is working fine...i think it just wasnt keen on not using the same drive letter on win as SW
