### ISSUE TITLE
StormLoader wont connect - Change SQL hostname to portal.stormloader.uk from dynamic hostname 

### ISSUE THREAD

**Issue by lumiini** [Lewinator56/StormLoader#4]
When ever I try to open the repo list it says could not connect!

**Comment by Yogie489** [comment]
Same here. I tried redownloading and I cannot connect to the repo.

**Comment by gaby2013** [comment]
Same here

**Comment by Lewinator56** [comment]
it may be a firewall or antivirus issue, ill take a look at your log if you want

**Comment by lumiini** [comment]
Nope not it already did that!

**Comment by stinkycat67** [comment]
it is also saying that it wont connect for me

**Comment by Lewinator56** [comment]
Hostname expired, its fixed now, I need to change it to use the IP rather than a dynamic hostname, i wont close this as its something I need to do

**Comment by lumiini** [comment]
Thx

**Comment by Lewinator56** [comment]
I'm re-opening this because I haven't enacted the change yet

**Comment by Lewinator56** [comment]
Changed to server IP as of v1.1
