### ISSUE TITLE
An error occured: Root element is missing

### ISSUE THREAD

**Issue by wFirbolg** [Lewinator56/StormLoader#5]
This is probably something I did wrong but when I try to add anything from the repository, a window opens and says root element is missing and stormloader exits. Thanks for any tips on what I'm doing wrong. Cheers

[log.txt](https://github.com/Lewinator56/StormLoader/files/7272892/log.txt)

**Comment by Lewinator56** [comment]
i cant replicate this, but ill look into it. i suggest for now try rebooting, it may be a windows bug.

**Comment by wFirbolg** [comment]
Thanks, man! I did! Still not working but it must be something on my end. It was working fine until this morning. Thank you for replying.

**Comment by Lewinator56** [comment]
can you locate the file 'CurrentProfile.xml'

i believe there may be a profile issue.

**Comment by wFirbolg** [comment]
I can but it's empty! I'll delete everything and start fresh.

**Comment by wFirbolg** [comment]
Still not working. Thanks for help anyway!
