### ISSUE TITLE
The EXE file doesnt exist

### ISSUE THREAD

**Issue by papi-realio** [Lewinator56/StormLoader#6]
I looked all over the files downloaded and couldn't find the EXE file. All of the tutorials I could find on downloading StormLoader mention using a EXE file but I dont see any on my download Is this the wrong file or am I just blind

**Comment by Lewinator56** [comment]
youve probably pulled the source code, you need to go to 'releases' and download the zip

**Comment by Lewinator56** [comment]
https://github.com/Lewinator56/StormLoader/releases/tag/v1.0.12

**Comment by papi-realio** [comment]
yeah i think i did lol im new to github i made an account just for this
