### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by TylerPritts** [Lewinator56/StormLoader#8]
I'm a Linux user, and it would be great if this could be compiled with Avalonia and .NET 6. The current version does not seem to work with Wine.

**Comment by Lewinator56** [comment]
Unfortunately, I have no plans for linux support, not until WPF gets support in linux, for now, you can run it, im not sure how functional it will be though, through WINE by following the instructions here: https://old.reddit.com/r/linux4noobs/comments/firqs9/getting_windows_wpf_applications_to_run_with_wine/
