### ISSUE TITLE
"Root element does not exist" - install_info error

### ISSUE THREAD

**Issue by HerrMon** [Lewinator56/StormLoader#9]
Hello.
Yesterday I turned of my mods by clicking the grey X. Today I wanted to turn them back on, it worked. Ingame I noticed that a mod is missing (the other mods are working). I again opened the Stormloader and tried to install the missing mod via the grey checkmark which crashed Stormloader with the error window: "Das Stammelement ist nicht vorhanden." which roughly means (google translate) "The root element does not exist." 
The attached files are a screenshot of the error message and the stormloader log.
![error](https://user-images.githubusercontent.com/108390121/176390640-6225ed86-e3c8-4dd0-be56-11b9acbc54ec.png)
[log.txt](https://github.com/Lewinator56/StormLoader/files/9008722/log.txt)

**Comment by Lewinator56** [comment]
This is a common bug, its a duplicate (with a different error) of this: https://github.com/Lewinator56/StormLoader/issues/7 .

To fix it temporarily, go to the stormworks directory, find and delete 'stormloader_install_info.xml' then re-install all the mods you previously had installed and then uninstall the ones you want. (the re-install is required to rebuild the XML,, files wont be copied as they already exist without it stormloader cant uninstall mods)

**Comment by HerrMon** [comment]
Thanks for the fast reply! I will try this.
